// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestProto.proto

package io.github.lamtong.easylock.common.core;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string application = 2;</code>
     * @return The application.
     */
    java.lang.String getApplication();
    /**
     * <code>string application = 2;</code>
     * @return The bytes for application.
     */
    com.google.protobuf.ByteString
        getApplicationBytes();

    /**
     * <code>string thread = 3;</code>
     * @return The thread.
     */
    java.lang.String getThread();
    /**
     * <code>string thread = 3;</code>
     * @return The bytes for thread.
     */
    com.google.protobuf.ByteString
        getThreadBytes();

    /**
     * <code>int64 identity = 4;</code>
     * @return The identity.
     */
    long getIdentity();

    /**
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>bool lockRequest = 6;</code>
     * @return The lockRequest.
     */
    boolean getLockRequest();

    /**
     * <code>bool tryLock = 7;</code>
     * @return The tryLock.
     */
    boolean getTryLock();

    /**
     * <code>int64 time = 8;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>bool readLock = 9;</code>
     * @return The readLock.
     */
    boolean getReadLock();
  }
  /**
   * Protobuf type {@code RequestProto}
   */
  public static final class RequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestProto)
      RequestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestProto.newBuilder() to construct.
    private RequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProto() {
      key_ = "";
      application_ = "";
      thread_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              application_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              thread_ = s;
              break;
            }
            case 32: {

              identity_ = input.readInt64();
              break;
            }
            case 40: {

              type_ = input.readInt32();
              break;
            }
            case 48: {

              lockRequest_ = input.readBool();
              break;
            }
            case 56: {

              tryLock_ = input.readBool();
              break;
            }
            case 64: {

              time_ = input.readInt64();
              break;
            }
            case 72: {

              readLock_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.lamtong.easylock.common.core.Request.internal_static_RequestProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.lamtong.easylock.common.core.Request.internal_static_RequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.lamtong.easylock.common.core.Request.RequestProto.class, io.github.lamtong.easylock.common.core.Request.RequestProto.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLICATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object application_;
    /**
     * <code>string application = 2;</code>
     * @return The application.
     */
    @java.lang.Override
    public java.lang.String getApplication() {
      java.lang.Object ref = application_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        application_ = s;
        return s;
      }
    }
    /**
     * <code>string application = 2;</code>
     * @return The bytes for application.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApplicationBytes() {
      java.lang.Object ref = application_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        application_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREAD_FIELD_NUMBER = 3;
    private volatile java.lang.Object thread_;
    /**
     * <code>string thread = 3;</code>
     * @return The thread.
     */
    @java.lang.Override
    public java.lang.String getThread() {
      java.lang.Object ref = thread_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        thread_ = s;
        return s;
      }
    }
    /**
     * <code>string thread = 3;</code>
     * @return The bytes for thread.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThreadBytes() {
      java.lang.Object ref = thread_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thread_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITY_FIELD_NUMBER = 4;
    private long identity_;
    /**
     * <code>int64 identity = 4;</code>
     * @return The identity.
     */
    @java.lang.Override
    public long getIdentity() {
      return identity_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int LOCKREQUEST_FIELD_NUMBER = 6;
    private boolean lockRequest_;
    /**
     * <code>bool lockRequest = 6;</code>
     * @return The lockRequest.
     */
    @java.lang.Override
    public boolean getLockRequest() {
      return lockRequest_;
    }

    public static final int TRYLOCK_FIELD_NUMBER = 7;
    private boolean tryLock_;
    /**
     * <code>bool tryLock = 7;</code>
     * @return The tryLock.
     */
    @java.lang.Override
    public boolean getTryLock() {
      return tryLock_;
    }

    public static final int TIME_FIELD_NUMBER = 8;
    private long time_;
    /**
     * <code>int64 time = 8;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }

    public static final int READLOCK_FIELD_NUMBER = 9;
    private boolean readLock_;
    /**
     * <code>bool readLock = 9;</code>
     * @return The readLock.
     */
    @java.lang.Override
    public boolean getReadLock() {
      return readLock_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(application_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, application_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thread_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, thread_);
      }
      if (identity_ != 0L) {
        output.writeInt64(4, identity_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      if (lockRequest_ != false) {
        output.writeBool(6, lockRequest_);
      }
      if (tryLock_ != false) {
        output.writeBool(7, tryLock_);
      }
      if (time_ != 0L) {
        output.writeInt64(8, time_);
      }
      if (readLock_ != false) {
        output.writeBool(9, readLock_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(application_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, application_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thread_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, thread_);
      }
      if (identity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, identity_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (lockRequest_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, lockRequest_);
      }
      if (tryLock_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, tryLock_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, time_);
      }
      if (readLock_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, readLock_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.lamtong.easylock.common.core.Request.RequestProto)) {
        return super.equals(obj);
      }
      io.github.lamtong.easylock.common.core.Request.RequestProto other = (io.github.lamtong.easylock.common.core.Request.RequestProto) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getApplication()
          .equals(other.getApplication())) return false;
      if (!getThread()
          .equals(other.getThread())) return false;
      if (getIdentity()
          != other.getIdentity()) return false;
      if (getType()
          != other.getType()) return false;
      if (getLockRequest()
          != other.getLockRequest()) return false;
      if (getTryLock()
          != other.getTryLock()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getReadLock()
          != other.getReadLock()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + APPLICATION_FIELD_NUMBER;
      hash = (53 * hash) + getApplication().hashCode();
      hash = (37 * hash) + THREAD_FIELD_NUMBER;
      hash = (53 * hash) + getThread().hashCode();
      hash = (37 * hash) + IDENTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdentity());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + LOCKREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLockRequest());
      hash = (37 * hash) + TRYLOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTryLock());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + READLOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReadLock());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Request.RequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.lamtong.easylock.common.core.Request.RequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestProto)
        io.github.lamtong.easylock.common.core.Request.RequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.lamtong.easylock.common.core.Request.internal_static_RequestProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.lamtong.easylock.common.core.Request.internal_static_RequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.lamtong.easylock.common.core.Request.RequestProto.class, io.github.lamtong.easylock.common.core.Request.RequestProto.Builder.class);
      }

      // Construct using io.github.lamtong.easylock.common.core.Request.RequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        application_ = "";

        thread_ = "";

        identity_ = 0L;

        type_ = 0;

        lockRequest_ = false;

        tryLock_ = false;

        time_ = 0L;

        readLock_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.lamtong.easylock.common.core.Request.internal_static_RequestProto_descriptor;
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Request.RequestProto getDefaultInstanceForType() {
        return io.github.lamtong.easylock.common.core.Request.RequestProto.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Request.RequestProto build() {
        io.github.lamtong.easylock.common.core.Request.RequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Request.RequestProto buildPartial() {
        io.github.lamtong.easylock.common.core.Request.RequestProto result = new io.github.lamtong.easylock.common.core.Request.RequestProto(this);
        result.key_ = key_;
        result.application_ = application_;
        result.thread_ = thread_;
        result.identity_ = identity_;
        result.type_ = type_;
        result.lockRequest_ = lockRequest_;
        result.tryLock_ = tryLock_;
        result.time_ = time_;
        result.readLock_ = readLock_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.lamtong.easylock.common.core.Request.RequestProto) {
          return mergeFrom((io.github.lamtong.easylock.common.core.Request.RequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.lamtong.easylock.common.core.Request.RequestProto other) {
        if (other == io.github.lamtong.easylock.common.core.Request.RequestProto.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getApplication().isEmpty()) {
          application_ = other.application_;
          onChanged();
        }
        if (!other.getThread().isEmpty()) {
          thread_ = other.thread_;
          onChanged();
        }
        if (other.getIdentity() != 0L) {
          setIdentity(other.getIdentity());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getLockRequest() != false) {
          setLockRequest(other.getLockRequest());
        }
        if (other.getTryLock() != false) {
          setTryLock(other.getTryLock());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getReadLock() != false) {
          setReadLock(other.getReadLock());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.lamtong.easylock.common.core.Request.RequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.lamtong.easylock.common.core.Request.RequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object application_ = "";
      /**
       * <code>string application = 2;</code>
       * @return The application.
       */
      public java.lang.String getApplication() {
        java.lang.Object ref = application_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          application_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string application = 2;</code>
       * @return The bytes for application.
       */
      public com.google.protobuf.ByteString
          getApplicationBytes() {
        java.lang.Object ref = application_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          application_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string application = 2;</code>
       * @param value The application to set.
       * @return This builder for chaining.
       */
      public Builder setApplication(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        application_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string application = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplication() {
        
        application_ = getDefaultInstance().getApplication();
        onChanged();
        return this;
      }
      /**
       * <code>string application = 2;</code>
       * @param value The bytes for application to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        application_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object thread_ = "";
      /**
       * <code>string thread = 3;</code>
       * @return The thread.
       */
      public java.lang.String getThread() {
        java.lang.Object ref = thread_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          thread_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string thread = 3;</code>
       * @return The bytes for thread.
       */
      public com.google.protobuf.ByteString
          getThreadBytes() {
        java.lang.Object ref = thread_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thread_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string thread = 3;</code>
       * @param value The thread to set.
       * @return This builder for chaining.
       */
      public Builder setThread(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        thread_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string thread = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearThread() {
        
        thread_ = getDefaultInstance().getThread();
        onChanged();
        return this;
      }
      /**
       * <code>string thread = 3;</code>
       * @param value The bytes for thread to set.
       * @return This builder for chaining.
       */
      public Builder setThreadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        thread_ = value;
        onChanged();
        return this;
      }

      private long identity_ ;
      /**
       * <code>int64 identity = 4;</code>
       * @return The identity.
       */
      @java.lang.Override
      public long getIdentity() {
        return identity_;
      }
      /**
       * <code>int64 identity = 4;</code>
       * @param value The identity to set.
       * @return This builder for chaining.
       */
      public Builder setIdentity(long value) {
        
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 identity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentity() {
        
        identity_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean lockRequest_ ;
      /**
       * <code>bool lockRequest = 6;</code>
       * @return The lockRequest.
       */
      @java.lang.Override
      public boolean getLockRequest() {
        return lockRequest_;
      }
      /**
       * <code>bool lockRequest = 6;</code>
       * @param value The lockRequest to set.
       * @return This builder for chaining.
       */
      public Builder setLockRequest(boolean value) {
        
        lockRequest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool lockRequest = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLockRequest() {
        
        lockRequest_ = false;
        onChanged();
        return this;
      }

      private boolean tryLock_ ;
      /**
       * <code>bool tryLock = 7;</code>
       * @return The tryLock.
       */
      @java.lang.Override
      public boolean getTryLock() {
        return tryLock_;
      }
      /**
       * <code>bool tryLock = 7;</code>
       * @param value The tryLock to set.
       * @return This builder for chaining.
       */
      public Builder setTryLock(boolean value) {
        
        tryLock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool tryLock = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTryLock() {
        
        tryLock_ = false;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 8;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 8;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private boolean readLock_ ;
      /**
       * <code>bool readLock = 9;</code>
       * @return The readLock.
       */
      @java.lang.Override
      public boolean getReadLock() {
        return readLock_;
      }
      /**
       * <code>bool readLock = 9;</code>
       * @param value The readLock to set.
       * @return This builder for chaining.
       */
      public Builder setReadLock(boolean value) {
        
        readLock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool readLock = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearReadLock() {
        
        readLock_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestProto)
    }

    // @@protoc_insertion_point(class_scope:RequestProto)
    private static final io.github.lamtong.easylock.common.core.Request.RequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.lamtong.easylock.common.core.Request.RequestProto();
    }

    public static io.github.lamtong.easylock.common.core.Request.RequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProto>
        PARSER = new com.google.protobuf.AbstractParser<RequestProto>() {
      @java.lang.Override
      public RequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.lamtong.easylock.common.core.Request.RequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RequestProto.proto\"\246\001\n\014RequestProto\022\013\n" +
      "\003key\030\001 \001(\t\022\023\n\013application\030\002 \001(\t\022\016\n\006threa" +
      "d\030\003 \001(\t\022\020\n\010identity\030\004 \001(\003\022\014\n\004type\030\005 \001(\005\022" +
      "\023\n\013lockRequest\030\006 \001(\010\022\017\n\007tryLock\030\007 \001(\010\022\014\n" +
      "\004time\030\010 \001(\003\022\020\n\010readLock\030\t \001(\010B1\n&io.gith" +
      "ub.lamtong.easylock.common.coreB\007Request" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProto_descriptor,
        new java.lang.String[] { "Key", "Application", "Thread", "Identity", "Type", "LockRequest", "TryLock", "Time", "ReadLock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
