// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseProto.proto

package io.github.lamtong.easylock.common.core;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>int64 identity = 2;</code>
     * @return The identity.
     */
    long getIdentity();

    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string cause = 4;</code>
     * @return The cause.
     */
    java.lang.String getCause();
    /**
     * <code>string cause = 4;</code>
     * @return The bytes for cause.
     */
    com.google.protobuf.ByteString
        getCauseBytes();

    /**
     * <code>bool lockResponse = 5;</code>
     * @return The lockResponse.
     */
    boolean getLockResponse();
  }
  /**
   * Protobuf type {@code ResponseProto}
   */
  public static final class ResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseProto)
      ResponseProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseProto.newBuilder() to construct.
    private ResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProto() {
      key_ = "";
      cause_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 16: {

              identity_ = input.readInt64();
              break;
            }
            case 24: {

              success_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cause_ = s;
              break;
            }
            case 40: {

              lockResponse_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.lamtong.easylock.common.core.Response.internal_static_ResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.lamtong.easylock.common.core.Response.internal_static_ResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.lamtong.easylock.common.core.Response.ResponseProto.class, io.github.lamtong.easylock.common.core.Response.ResponseProto.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITY_FIELD_NUMBER = 2;
    private long identity_;
    /**
     * <code>int64 identity = 2;</code>
     * @return The identity.
     */
    @java.lang.Override
    public long getIdentity() {
      return identity_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int CAUSE_FIELD_NUMBER = 4;
    private volatile java.lang.Object cause_;
    /**
     * <code>string cause = 4;</code>
     * @return The cause.
     */
    @java.lang.Override
    public java.lang.String getCause() {
      java.lang.Object ref = cause_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cause_ = s;
        return s;
      }
    }
    /**
     * <code>string cause = 4;</code>
     * @return The bytes for cause.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCauseBytes() {
      java.lang.Object ref = cause_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCKRESPONSE_FIELD_NUMBER = 5;
    private boolean lockResponse_;
    /**
     * <code>bool lockResponse = 5;</code>
     * @return The lockResponse.
     */
    @java.lang.Override
    public boolean getLockResponse() {
      return lockResponse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (identity_ != 0L) {
        output.writeInt64(2, identity_);
      }
      if (success_ != false) {
        output.writeBool(3, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cause_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cause_);
      }
      if (lockResponse_ != false) {
        output.writeBool(5, lockResponse_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (identity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, identity_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cause_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cause_);
      }
      if (lockResponse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, lockResponse_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.lamtong.easylock.common.core.Response.ResponseProto)) {
        return super.equals(obj);
      }
      io.github.lamtong.easylock.common.core.Response.ResponseProto other = (io.github.lamtong.easylock.common.core.Response.ResponseProto) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (getIdentity()
          != other.getIdentity()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getCause()
          .equals(other.getCause())) return false;
      if (getLockResponse()
          != other.getLockResponse()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + IDENTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdentity());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + CAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getCause().hashCode();
      hash = (37 * hash) + LOCKRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLockResponse());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.lamtong.easylock.common.core.Response.ResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.lamtong.easylock.common.core.Response.ResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseProto)
        io.github.lamtong.easylock.common.core.Response.ResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.lamtong.easylock.common.core.Response.internal_static_ResponseProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.lamtong.easylock.common.core.Response.internal_static_ResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.lamtong.easylock.common.core.Response.ResponseProto.class, io.github.lamtong.easylock.common.core.Response.ResponseProto.Builder.class);
      }

      // Construct using io.github.lamtong.easylock.common.core.Response.ResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        identity_ = 0L;

        success_ = false;

        cause_ = "";

        lockResponse_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.lamtong.easylock.common.core.Response.internal_static_ResponseProto_descriptor;
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Response.ResponseProto getDefaultInstanceForType() {
        return io.github.lamtong.easylock.common.core.Response.ResponseProto.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Response.ResponseProto build() {
        io.github.lamtong.easylock.common.core.Response.ResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.lamtong.easylock.common.core.Response.ResponseProto buildPartial() {
        io.github.lamtong.easylock.common.core.Response.ResponseProto result = new io.github.lamtong.easylock.common.core.Response.ResponseProto(this);
        result.key_ = key_;
        result.identity_ = identity_;
        result.success_ = success_;
        result.cause_ = cause_;
        result.lockResponse_ = lockResponse_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.lamtong.easylock.common.core.Response.ResponseProto) {
          return mergeFrom((io.github.lamtong.easylock.common.core.Response.ResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.lamtong.easylock.common.core.Response.ResponseProto other) {
        if (other == io.github.lamtong.easylock.common.core.Response.ResponseProto.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getIdentity() != 0L) {
          setIdentity(other.getIdentity());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getCause().isEmpty()) {
          cause_ = other.cause_;
          onChanged();
        }
        if (other.getLockResponse() != false) {
          setLockResponse(other.getLockResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.lamtong.easylock.common.core.Response.ResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.lamtong.easylock.common.core.Response.ResponseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private long identity_ ;
      /**
       * <code>int64 identity = 2;</code>
       * @return The identity.
       */
      @java.lang.Override
      public long getIdentity() {
        return identity_;
      }
      /**
       * <code>int64 identity = 2;</code>
       * @param value The identity to set.
       * @return This builder for chaining.
       */
      public Builder setIdentity(long value) {
        
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 identity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentity() {
        
        identity_ = 0L;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 3;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 3;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object cause_ = "";
      /**
       * <code>string cause = 4;</code>
       * @return The cause.
       */
      public java.lang.String getCause() {
        java.lang.Object ref = cause_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cause_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cause = 4;</code>
       * @return The bytes for cause.
       */
      public com.google.protobuf.ByteString
          getCauseBytes() {
        java.lang.Object ref = cause_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cause = 4;</code>
       * @param value The cause to set.
       * @return This builder for chaining.
       */
      public Builder setCause(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cause_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cause = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCause() {
        
        cause_ = getDefaultInstance().getCause();
        onChanged();
        return this;
      }
      /**
       * <code>string cause = 4;</code>
       * @param value The bytes for cause to set.
       * @return This builder for chaining.
       */
      public Builder setCauseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cause_ = value;
        onChanged();
        return this;
      }

      private boolean lockResponse_ ;
      /**
       * <code>bool lockResponse = 5;</code>
       * @return The lockResponse.
       */
      @java.lang.Override
      public boolean getLockResponse() {
        return lockResponse_;
      }
      /**
       * <code>bool lockResponse = 5;</code>
       * @param value The lockResponse to set.
       * @return This builder for chaining.
       */
      public Builder setLockResponse(boolean value) {
        
        lockResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool lockResponse = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLockResponse() {
        
        lockResponse_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseProto)
    }

    // @@protoc_insertion_point(class_scope:ResponseProto)
    private static final io.github.lamtong.easylock.common.core.Response.ResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.lamtong.easylock.common.core.Response.ResponseProto();
    }

    public static io.github.lamtong.easylock.common.core.Response.ResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProto>() {
      @java.lang.Override
      public ResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.lamtong.easylock.common.core.Response.ResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ResponseProto.proto\"d\n\rResponseProto\022\013" +
      "\n\003key\030\001 \001(\t\022\020\n\010identity\030\002 \001(\003\022\017\n\007success" +
      "\030\003 \001(\010\022\r\n\005cause\030\004 \001(\t\022\024\n\014lockResponse\030\005 " +
      "\001(\010B2\n&io.github.lamtong.easylock.common" +
      ".coreB\010Responseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseProto_descriptor,
        new java.lang.String[] { "Key", "Identity", "Success", "Cause", "LockResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
